### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
Please release new version for Fluentd v0.12.x before merge this pull request.

**Comment by okkez** [comment]
Any progress?

**Comment by okkez** [comment]
@tagomoris ping?

**Comment by tagomoris** [comment]
@okkez Oops, I'm very sorry to miss this pull-req.
Right now, this plugin is outdated, and I don't recommend to use this plugin for anyone.
So that, I'll not merge this change and leave this plugin as-is.

**Comment by okkez** [comment]
OK, thanks!

**Pull request closed without merging**
